Task 01:
Your objective is to manually compute the slope (M) and y-intercept (C) using
Ordinary Least Squares Linear Regression. Once determined, apply these values to
predict the price when the vegetable weight is 6.
Task 02:
Compute the residuals for each data point.

Task 03:
Calculate both the Mean Squared Error (MSE) and Mean Absolute Error (MAE).

Final Task:
Generate an Excel file for the given dataset. Utilize Python for all the calculations.

Note: To validate your manual calculations, use the entire dataset. It's unnecessary
to split the dataset.

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = {"weight":[2,4,5,3,4,5,7],"price":[35,60,20,50,50,55,60]}
df = pd.DataFrame(data)
df.head(10)

weight  price
0       2     35
1       4     60
2       5     20
3       3     50
4       4     50
5       5     55
6       7     60

In [3]:
df["weight"]

0    2
1    4
2    5
3    3
4    4
5    5
6    7
Name: weight, dtype: int64

In [4]:
df[["weight"]]

weight
0       2
1       4
2       5
3       3
4       4
5       5
6       7

<font size="24" font-style="bold">Linear Regression(Manual)<font/>

In [5]:
x = df["weight"]
x_bar = np.mean(x)

In [6]:
y = df["price"]
y_bar = np.mean(y)
y_bar


47.142857142857146

In [7]:
numerator = np.sum((x-x_bar)*(y-y_bar))
denominator = np.sum((x-x_bar)**2)

In [8]:
numerator

40.71428571428572

In [9]:
denominator


15.42857142857143

In [10]:
m = numerator/denominator
m

2.6388888888888893

In [11]:
c = y_bar - (m * x_bar)
c

35.833333333333336

In [12]:
#Prediction
y_result = (m * 6) + c
y_result


51.66666666666667

<font size="24"> Residual<font/>

In [13]:
df

weight  price
0       2     35
1       4     60
2       5     20
3       3     50
4       4     50
5       5     55
6       7     60

In [14]:
df["price_predicted"] = (m * df.weight) + c


In [15]:
df

weight  price  price_predicted
0       2     35        41.111111
1       4     60        46.388889
2       5     20        49.027778
3       3     50        43.750000
4       4     50        46.388889
5       5     55        49.027778
6       7     60        54.305556

In [16]:
df["residuals"] = df.price_predicted - df.price

In [17]:
df

weight  price  price_predicted  residuals
0       2     35        41.111111   6.111111
1       4     60        46.388889 -13.611111
2       5     20        49.027778  29.027778
3       3     50        43.750000  -6.250000
4       4     50        46.388889  -3.611111
5       5     55        49.027778  -5.972222
6       7     60        54.305556  -5.694444

<font size="24">MSE<font/>

In [18]:
y

0    35
1    60
2    20
3    50
4    50
5    55
6    60
Name: price, dtype: int64

In [19]:
y_bar

47.142857142857146

In [20]:
mse = (np.sum((y-y_bar)**2))/len(df.columns)

In [21]:
mse

323.2142857142857

<font size="24">MAE<font/>

In [22]:
mae = (np.sum(abs(y-y_bar)))/len(df.columns)

In [23]:
mae

19.64285714285714

<font size="24" font-style="bold">DataFrame to Excel<font/>

In [24]:
df

weight  price  price_predicted  residuals
0       2     35        41.111111   6.111111
1       4     60        46.388889 -13.611111
2       5     20        49.027778  29.027778
3       3     50        43.750000  -6.250000
4       4     50        46.388889  -3.611111
5       5     55        49.027778  -5.972222
6       7     60        54.305556  -5.694444

In [25]:
df.to_excel("dataframe.xlsx",index=True)

<font size="24" font-style="bold">Linear Regression(SkLearn)<font/>

In [148]:
from sklearn.linear_model import LinearRegression


In [149]:
result.intercept_


array([35.83333333])

In [150]:
result = LinearRegression().fit(df_excel[["weight"]],df_excel[["price"]])
result

LinearRegression()

In [153]:
result.coef_


array([[2.63888889]])

In [155]:
result.predict([[6]])

array([[51.66666667]])