Task 01:
Your objective is to manually compute the slope (M) and y-intercept (C) using
Ordinary Least Squares Linear Regression. Once determined, apply these values to
predict the price when the vegetable weight is 6.
Task 02:
Compute the residuals for each data point.

Task 03:
Calculate both the Mean Squared Error (MSE) and Mean Absolute Error (MAE).

Final Task:
Generate an Excel file for the given dataset. Utilize Python for all the calculations.

Note: To validate your manual calculations, use the entire dataset. It's unnecessary
to split the dataset.

In [144]:
pip install pandas


Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Note: you may need to restart the kernel to use updated packages.


In [145]:
pip install numpy

^C
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages/pip/__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "/opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages/pip/_int

In [98]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [100]:
data = {"weight":[2,4,5,3,4,5,7],"price":[35,60,20,50,50,55,60]}
df = pd.DataFrame(data)
df.head(10)

weight  price
0       2     35
1       4     60
2       5     20
3       3     50
4       4     50
5       5     55
6       7     60

In [101]:
df["weight"]

0    2
1    4
2    5
3    3
4    4
5    5
6    7
Name: weight, dtype: int64

In [102]:
df[["weight"]]

weight
0       2
1       4
2       5
3       3
4       4
5       5
6       7

<font size="24" font-style="bold">Linear Regression(Manual)<font/>

In [103]:
x = df["weight"]
x_bar = np.mean(x)

In [106]:
y = df["price"]
y_bar = np.mean(y)
y_bar


47.142857142857146

In [108]:
numerator = np.sum((x-x_bar)*(y-y_bar))
denominator = np.sum((x-x_bar)**2)

In [110]:
numerator

40.71428571428572

In [111]:
denominator


15.42857142857143

In [112]:
m = numerator/denominator
m

2.6388888888888893

In [114]:
c = y_bar - (m * x_bar)
c

35.833333333333336

In [177]:
#Prediction
y_result = (m * 6) + c
y_result


51.66666666666667

<font size="24"> Residual<font/>

In [121]:
df

weight  price
0       2     35
1       4     60
2       5     20
3       3     50
4       4     50
5       5     55
6       7     60

In [122]:
df["price_predicted"] = (m * df.weight) + c


In [123]:
df

weight  price  price_predicted
0       2     35        41.111111
1       4     60        46.388889
2       5     20        49.027778
3       3     50        43.750000
4       4     50        46.388889
5       5     55        49.027778
6       7     60        54.305556

In [179]:
df["residuals"] = df.price_predicted - df.price

In [127]:
df

weight  price  price_predicted  residuals
0       2     35        41.111111   6.111111
1       4     60        46.388889 -13.611111
2       5     20        49.027778  29.027778
3       3     50        43.750000  -6.250000
4       4     50        46.388889  -3.611111
5       5     55        49.027778  -5.972222
6       7     60        54.305556  -5.694444

<font size="24">MSE<font/>

In [129]:
y

0    35
1    60
2    20
3    50
4    50
5    55
6    60
Name: price, dtype: int64

In [131]:
y_bar

47.142857142857146

In [133]:
mse = (np.sum((y-y_bar)**2))/len(df.columns)

In [135]:
mse

323.2142857142857

<font size="24">MAE<font/>

In [139]:
mae = (np.sum(abs(y-y_bar)))/len(df.columns)

In [140]:
mae

19.64285714285714

<font size="24" font-style="bold">DataFrame to Excel<font/>

In [142]:
df_excel = pd.DataFrame(data)
df_excel

weight  price
0       2     35
1       4     60
2       5     20
3       3     50
4       4     50
5       5     55
6       7     60

In [144]:
df_excel.to_excel("dataframe.xlsx",index=True)

<font size="24" font-style="bold">Linear Regression(SkLearn)<font/>

In [148]:
from sklearn.linear_model import LinearRegression


In [149]:
result.intercept_


array([35.83333333])

In [150]:
result = LinearRegression().fit(df_excel[["weight"]],df_excel[["price"]])
result

LinearRegression()

In [153]:
result.coef_


array([[2.63888889]])

In [155]:
result.predict([[6]])

array([[51.66666667]])